# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NearestGreater
                                 A QGIS plugin
 Get id of and distance to the nearest feature with greater value in a certain field.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-09-07
        copyright            : (C) 2022 by Florian Neukirchen
        email                : mail@riannek.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Florian Neukirchen'
__date__ = '2022-09-07'
__copyright__ = '(C) 2022 by Florian Neukirchen'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NearestGreater class from file NearestGreater.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .nearest_greater import NearestGreaterPlugin
    return NearestGreaterPlugin()
